version: "3"
services:
#  minio-srv:
#    restart: always
#    image: minio/minio
#    command: server --address ":9000" --console-address ":9001" /data
#    env_file:
#      - .env
#    environment:
#      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
#      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
#    ports:
#      - "9000:9000"
#      - "9001:9001"
#    volumes:
#      - ./miniodata:/data

  malcheck-dash:
    restart: always
    image: malcheck_dash:latest
    build:
        context: ./malcheck-dash
        dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - MINIO_HOST=${MINIO_HOST}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - CHAT_ID={CHAT_ID}
      - BOT_TOKEN={BOT_TOKEN}
      - DASH_USER={DASH_USER}
      - DASH_PASSWORD={DASH_PASSWORD}
      - SECRET_KEY={SECRET_KEY}
    ports:
      - "80:5000"
    volumes:
      - ./data/dbs:/app/dbs/
      - ./data/logs:/app/logs/
