version: "3"
services:
  malcheck-dash-nginx:
    restart: always
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
      - malcheck-dash
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf

  malcheck-dash:
    restart: always
    image: malcheck_dash:latest
    build:
        context: ./malcheck-dash
        dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - MINIO_HOST=${MINIO_HOST}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - CHAT_ID=${CHAT_ID}
      - BOT_TOKEN=${BOT_TOKEN}
      - DASH_USER=${DASH_USER}
      - DASH_PASSWORD=${DASH_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./data/db:/app/db/
      - ./data/log:/app/log/
